// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Context;

#nullable disable

namespace SalesManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230102160126_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SalesManagement.Models.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdProduto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProduto"), 1L, 1);

                    b.Property<string>("Descrição")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descrição");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("SalesManagement.Models.Venda", b =>
                {
                    b.Property<long>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdVenda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVenda"), 1L, 1);

                    b.Property<long>("VendedorId")
                        .HasColumnType("bigint");

                    b.HasKey("IdVenda");

                    b.HasIndex("VendedorId");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("SalesManagement.Models.VendaProduto", b =>
                {
                    b.Property<long>("VendaId")
                        .HasColumnType("bigint")
                        .HasColumnName("VendaId");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProdutoId");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.HasKey("VendaId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("VendaProduto", (string)null);
                });

            modelBuilder.Entity("SalesManagement.Models.Vendedor", b =>
                {
                    b.Property<long>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdVendedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVendedor"), 1L, 1);

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Comissao");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Documento");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedores", (string)null);
                });

            modelBuilder.Entity("SalesManagement.Models.Venda", b =>
                {
                    b.HasOne("SalesManagement.Models.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SalesManagement.Models.VendaProduto", b =>
                {
                    b.HasOne("SalesManagement.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagement.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("SalesManagement.Models.Vendedor", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
